enum Pasaran {
  Bangkok = 'Bangkok',
  Brazil = 'Brazil',
  Brunei = 'Brunei',
  Busan = 'Busan',
  Cambodia = 'Cambodia',
  Denmark = 'Denmark',
  France = 'France',
  Germany = 'Germany',
  Hongkong = 'Hongkong',
  HuaHin = 'HuaHin',
  Hungary = 'Hungary',
  India = 'India',
  Mexico = 'Mexico',
  Malaysia = 'Malaysia',
  Mongolia = 'Mongolia',
  Myanmar = 'Myanmar',
  Osaka = 'Osaka',
  Philippines = 'Philippines',
  Poland = 'Poland',
  Seoul = 'Seoul',
  Singapore = 'Singapore',
  Sweden = 'Sweden',
  Sydney = 'Sydney',
  Taiwan = 'Taiwan',
  TimorLeste = 'TimorLeste',
  Vietnam = 'Vietnam',
}

export { Pasaran };
